### ISSUE TITLE
Is rendering .md in <iframe> possible?

### ISSUE THREAD

**Issue by defdefred** [simov/markdown-viewer#102] opened 2019-11-29 13:27 UTC
example:

<!DOCTYPE html>
<html>
<body>
<iframe name="menu" width="128" src="menu.md">
  <p>Your browser does not support iframes.</p>
</iframe>
</iframe><iframe name="article" src="welcome.md">
  <p>Your browser does not support iframes.</p>
</iframe>

</body>
</html>

**Comment by simov** [comment] 2019-12-01 14:47
I don't think that's currently possible.

**Comment by simov** [comment] 2023-03-18 09:42
Duplicate of https://github.com/simov/markdown-viewer/issues/83

**Closed by simov** 2023-03-18 09:42 UTC
Labels: feature
