### ISSUE TITLE
Navigate local files does not show the beginning of the file

### ISSUE THREAD

**Issue by aanton** [simov/markdown-viewer#11] opened 2017-01-20 06:22 UTC
If a markdown local file has got links to other markdown local files, when clicked the new page does not show the beginning of the file. It seems it keep the current scroll position of the previous file.

Regards,
Armando

**Comment by simov** [comment] 2017-01-20 08:08
Yep, I know about this problem. I have an idea on how to fix it. I'll let you know when it's done.

**Comment by simov** [comment] 2017-01-23 13:38
I just published version 2.5 where among other things now the extension stores the scroll position for each markdown file individually. You can also disable that option altogether. Let me know what do you think.

You should receive the update after about an hour.

**Comment by aanton** [comment] 2017-01-24 07:29
I would like a behaviour similar than the browsers:
* When a link is clicked, the new page is displayed without scroll
* Links can have a fragment to force the scroll to the desired point
* When navigating back & forward in the browser, the scroll is kept

What do you think?

**Comment by simov** [comment] 2017-01-24 13:56
I think the second point is doable. Although it may break the current behavior in some cases, see point three below.

The third one should work as expected if you have the scroll option enabled, because in the latest version the scroll position is saved for each page individually.

The first one will be tricky. The idea behind the scroll option is to keep the scroll position after you reload the page, for example while editing the document, and for example if you read a really long document and you want to start from where you left off.

The problem is that there is no way for me to know if you want to see the page top or not.

**Comment by aanton** [comment] 2017-01-24 16:57
My previous comments were related to use the markdown files in "read mode". I understand that the "live/preview mode" has other needs.

Would it make sense to have two different modes?

1. Live mode, the default one, it would keep the scroll of each file
2. Read mode, it would behave like a normal web page navigation

Regards

**Comment by simov** [comment] 2017-01-24 17:53
This is what can be done easily:

#### Live mode (the scroll option is enabled):

- the scroll position is remembered and enforced **always**

#### Read mode (the scroll option is disabled):

- **always** render at the top of the page
- if there is a fragment present in the URL, then scroll to it *(this should be implemented)*

As far as the back/forward history goes, like I said earlier that would be tricky, meaning that the page will be either at the top or at the fragment when the scroll option is disabled, or at the previous scroll position otherwise.

**Comment by aanton** [comment] 2017-01-24 18:11
It sounds OK for me :)

**Comment by simov** [comment] 2017-01-25 10:46
OK, I'll let you know when it's ready. I'm cooking some other small fixes as well.

**Comment by simov** [comment] 2017-01-26 11:22
Landed in version 2.6 :rocket: I also updated the docs with a little bit of [info](https://github.com/simov/markdown-viewer#content-options) about it.

Thanks for the feedback :+1:

**Closed by simov** 2017-01-26 11:22 UTC

**Comment by aanton** [comment] 2017-01-26 12:53
Great! Thanks
